
title: My Resume
url: 'https://junlulocky.com'
baseurl: '/PanelCV' #change it according to your repository name



# Profile information
yourname: Bharat Dadwaria  ## put your name
title: 'Integrated M.Sc Computer Science Major in AI'  ## your title
location: Central University of Rajasthan , India

#seo plugin
plugins: 
  - jekyll-seo-tag


## Social Profiles
facebook: https://www.facebook.com/bharat.dadwaria  ## your facebook account url
twitter: https://www.twitter.com/@BKDdadwaria  ## your twitter account url
linkedin: https://www.linkedin.com/in/dadwariabharat  ## your linkedin account url
github: https://github.com/bharatdadwaria/ #your github account url
dribbble: https://www.dribble.com  ## you dribbble account url
foursquare: https://www.foursquare.com  ## your foursquare account url



# Update all the sections by editing the files inside _includes folder.
