
title: My Resume
url: 'http://junlulocky.com'
baseurl: '/PanelCV' #change it according to your repository name



# Profile information
yourname: Bharat Dadwaria  ## put your name
title: 'Integrated M.Sc Computer Science Major in AI'  ## your title
location: Central University of Rajasthan , India

#seo plugin
plugins: 
  -jekyll-seo-tag


## Social Profiles
facebook: http://www.facebook.com/bharat.dadwaria  ## your facebook account url
twitter: http://www.twitter.com/@BKDdadwaria  ## your twitter account url
linkedin: http://www.linkedin.com/in/dadwariabharat  ## your linkedin account url
github: http://github.com/bkd0385/ #your github account url
dribbble: http://www.dribble.com  ## you dribbble account url
foursquare: http://www.foursquare.com  ## your foursquare account url



# Update all the sections by editing the files inside _includes folder.
